<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FeshShop.Common.Authentication\FeshShop.Common.Authentication.csproj" />
    <ProjectReference Include="..\FeshShop.Common.Guard\FeshShop.Common.Guard.csproj" />
    <ProjectReference Include="..\FeshShop.Common.Logging\FeshShop.Common.Logging.csproj" />
    <ProjectReference Include="..\FeshShop.Common.Mediator\FeshShop.Common.Mediator.csproj" />
    <ProjectReference Include="..\FeshShop.Common.Swagger\FeshShop.Common.Swagger.csproj" />
    <ProjectReference Include="..\FeshShop.Common.Types\FeshShop.Common.Types.csproj" />
  </ItemGroup>
</Project>