<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FeshShop.Common.Mediator\FeshShop.Common.Mediator.csproj" />
      <ProjectReference Include="..\FeshShop.Common\FeshShop.Common.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Scrutor" Version="6.0.1" />
    </ItemGroup>

</Project>
