<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\FeshShop.Common.Mongo\FeshShop.Common.Mongo.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AspNetCore.HealthChecks.MongoDb" Version="9.0.0" />
      <PackageReference Include="AspNetCore.HealthChecks.UI.Client" Version="9.0.0" />
    </ItemGroup>

</Project>
